about/urls.py
from django.urls import path
from . import views

app_name = "about"

urlpatterns = [
    path('', views.AboutPage.as_view(), name="about"),
]

blog/urls.py
from django.urls import path
from . import views


app_name = "blog"

urlpatterns = [
    path('', views.BlogPage.as_view(), name="blogs"),
]

contacts/urls.py
from django.urls import path
from . import views


app_name = "contacts"

urlpatterns = [
    path('', views.ContactsPage.as_view(), name="contacts")
]

dentistry/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('about/', include('about.urls')),
    path('services/', include('services.urls')),
    path('blog/', include('blog.urls')),
    path('contacts/', include('contacts.urls')),
    path('gallery/', include('gallery.urls')),
    path('patients/', include('patients.urls')),
]

gallery/urls.py
from django.urls import path
from . import views


app_name = "gallery"

urlpatterns = [
    path('', views.GalleryView.as_view(), name="gallery")
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.HomePage.as_view(), name='home'),
]

patients/urls.py
# from django.urls import nko
from django.urls import path
from . import views


app_name = "patients"

urlpatterns = [
    path('', views.PatientsPage.as_view(), name="patients")
]

services/urls.py
from django.urls import path
from . import views

app_name = "services"

urlpatterns = [
    path('', views.ServicesPage.as_view(), name="services"),
    path('<slug:slug>/', views.ServicesPage.as_view(), name="service")
]

about/models.py
from django.db import models


class About(models.Model):
    heading = models.CharField(max_length=25)
    image_1 = models.ImageField(upload_to='about/about/')
    image_2 = models.ImageField(upload_to='about/about/')
    content = models.TextField()

    class Meta:
        verbose_name = 'About Us'
        verbose_name_plural = 'About Us'


class ReasonToChooseUs(models.Model):
    heading = models.CharField(max_length=25, unique=True)
    image = models.ImageField(upload_to='about/reasons/')
    content = models.TextField()

    class Meta:
        verbose_name = 'Why Choose Us'
        verbose_name_plural = 'Why Choose Us'

    

blog/models.py
from django.db import models

# Create your models here.

contacts/models.py
from django.db import models

# Create your models here.

gallery/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models


class SlideShow(models.Model):
    slide_no = models.IntegerField()
    heading = models.TextField()
    sub_heading = models.TextField()
    image = models.ImageField(upload_to='home/sliders/')
    publish = models.BooleanField(default=False)


    class Meta:
        verbose_name = 'Slide Show'
        verbose_name_plural = 'Slide Show'

    def __str__(self):
        return f'Slide {self.slide_no}'


class HelpBox(models.Model):
    heading = models.CharField(max_length=25, unique=True)
    content = models.TextField() 

    class Meta:
        verbose_name = 'Help Box'
        verbose_name_plural = 'Help Boxes'

    def __str__(self):
        return self.heading


class OpeningHours(models.Model):
    period = models.CharField(max_length=25, unique=True)
    opening = models.TimeField()
    closing = models.TimeField()

    class Meta:
        verbose_name = 'Opening Hours'
        verbose_name_plural = 'Opening Hours'

    def __str__(self):
        return self.period


class WelcomeMessage(models.Model):
    heading = models.CharField(max_length=25)
    content = models.TextField()

    class Meta:
        verbose_name = 'Welcome Message'
        verbose_name_plural = 'Welcome Message'

    def __str__(self):
        return self.heading

patients/models.py
from django.db import models

# Create your models here.

services/models.py
from django.db import models


class ReasonToChooseUs(models.Model):
    heading = models.CharField(max_length=25, unique=True)
    image = models.ImageField(upload_to='about/reasons/')
    content = models.TextField()

    class Meta:
        verbose_name = 'Why Choose Us'
        verbose_name_plural = 'Why Choose Us'

about/views.py
from django.views.generic import TemplateView



class AboutPage(TemplateView):
    template_name = "about/about.html"

blog/views.py
from django.views.generic import TemplateView



class BlogPage(TemplateView):
    template_name = "blog/blog.html"

contacts/views.py
from django.views.generic import TemplateView



class ContactsPage(TemplateView):
    template_name = "contacts/contacts.html"

gallery/views.py
from django.views.generic import TemplateView


class GalleryView(TemplateView):
    pass

home/views.py
from django.views.generic import TemplateView


class HomePage(TemplateView):
    template_name = "home/home.html"

patients/views.py
from django.views.generic import TemplateView


class PatientsPage(TemplateView):
    template_name = "patients/patient.html"

services/views.py
from django.views.generic import TemplateView



class ServicesPage(TemplateView):
    template_name = "services/services.html"

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<title>House of Dentistry</title>
		<!--meta-->
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
		<meta name="format-detection" content="telephone=no" />
		<meta name="keywords" content="Dentist, Dentistry, Nairobi, Kenya" />
		<meta name="description" content="House of Dentistry Website" />
        <!--style-->
        <link href="https://fonts.googleapis.com/css?family=Titillium+Web&display=swap" rel="stylesheet"> 
		<link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.css' %}" />
		<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
        <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" />
        
        {% block custom_style %}
            
        {% endblock custom_style %}
            
		
	</head>
	<body class="body" style="font-family: 'Titillium Web', sans-serif;">
        <!-- Navigation -->
        <nav class="navbar navbar-expand-lg navbar-light bg-white">
            <div class="w-100 order-1 order-md-0 dual-collapse2">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button>
                <a style="margin-left: 12rem;" class="navbar-brand" href="#">House Of Dentistry</a>
            </div>
            <!-- <div class="w-50 order-0 order-md-0 dual-collapse2">&nbsp;</div> -->
            <div class="collapse navbar-collapse w-100 order-0 dual-collapse2" id="navbarTogglerDemo03" style="text-align: right;">
                <a class="nav-item nav-link active" id="home" href="{% url 'home:home' %}">Home</a>         
                <a class="nav-item nav-link" id="about" href="{% url 'about:about' %}">About</a>         
                <a class="nav-item nav-link" id="services" href="{% url 'services:services' %}">Services</a>         
                <a class="nav-item nav-link" id="gallery" href="{% url 'gallery:gallery' %}">Gallery</a>         
                <a class="nav-item nav-link" id="patients" href="{% url 'patients:patients' %}">Resources</a>         
                <a class="nav-item nav-link" id="blog" href="{% url 'blog:blogs' %}">Blog</a>         
                <a class="nav-item nav-link" id="contacts" href="{% url 'contacts:contacts' %}">Contacts</a>         
            </div>
        </nav>
        <div class="content">
            
            {% block content %}
                
            {% endblock content %}
        </div>
              
    <!--js-->
    <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/main.js' %}"></script>
    
    {% block custom_js %}
        
    {% endblock custom_js %}

</div>
        
    </body>
</html>
                